

test_account_data = [
    {
        "id": "0123232445",
        "email": "peterparker@avengers.com",
        "password": 'parkerPeter321',
        "first_name":"Peter",
        "middle_name":"",
        "last_name":"Parker",
        "mobile_phone":"851-237-4564",
        "mobile_notification":"True",
        "shoe_size":"8.5",
        "size_gender":"Male",
        "favorite_brand":"Nike",
        "postcode": "11431",
        "address_line": "2131 Wooster Ave",
        "address_line2": "",
        "apartment_suite_number": "13G",
        "town_city": "Sunnyside",
        "state": "NY",
        "delivery_instructions": "",
   },
   {
        "id": "1132343477",
        "email": "Lhowlett@gmail.com",
        "password": '1BadWolverine!',
        "first_name":"Logan",
        "middle_name":"W",
        "last_name":"Howlett",
        "mobile_phone":"518-321-0921",
        "mobile_notification":"True",
        "shoe_size":"9",
        "size_gender":"Male",
        "favorite_brand":"Puma",
        "postcode": "10560",
        "address_line": "1 Gifted Way",
        "address_line2": "",
        "apartment_suite_number": "",
        "town_city": "Salem Center",
        "state": "NY",
        "delivery_instructions": "",
   },
   {
        "id": "0987609876",
        "email": "srodgers@avengers.com",
        "password": 'Captain1Am!!',
        "first_name":"Steve",
        "middle_name":"G",
        "last_name":"Rodgers",
        "mobile_phone":"718-434-2211",
        "mobile_notification":"True",
        "shoe_size":"11.5",
        "size_gender":"Male",
        "favorite_brand":"Adidas",
        "postcode": "11228",
        "address_line": "1899 72nd Street",
        "address_line2": "",
        "apartment_suite_number": "First Floor",
        "town_city": "Bensonhurst",
        "state": "NY",
        "delivery_instructions": "",
   },
   {
        "id": "1231234567",
        "email": "tstark@avengers.com",
        "password": 'the1T@Starks',
        "first_name":"Anthony",
        "middle_name":"Edward",
        "last_name":"Stark",
        "mobile_phone":"212-345-3212",
        "mobile_notification":"True",
        "shoe_size":"10",
        "size_gender":"Male",
        "favorite_brand":"Gucci",
        "postcode": "11221",
        "address_line": "13 Park Ave",
        "address_line2": "",
        "apartment_suite_number": "PH",
        "town_city": "New York",
        "state": "NY",
        "delivery_instructions": "",
   },
   {
       "id": "5436577001",
        "email": "JCJones@aol.com",
        "password": '8adA$$Jess',
        "first_name":"Jessica",
        "middle_name":"C",
        "last_name":"Jones",
        "mobile_phone":"212-221-8453",
        "mobile_notification":"True",
        "shoe_size":"6",
        "size_gender":"Female",
        "favorite_brand":"Asics",
        "postcode": "10027",
        "address_line": "280 W 127th St",
        "address_line2": "",
        "apartment_suite_number": "7G",
        "town_city": "New York",
        "state": "NY",
        "delivery_instructions": "",
   },{
        "id": "0009998876",
        "email": "amarie@newmail.com",
        "password": 'AnMeLe$00',
        "first_name":"Anna Marie",
        "middle_name":"",
        "last_name":"LeBeau",
        "mobile_phone":"212-443-2145",
        "mobile_notification":"True",
        "shoe_size":"5",
        "size_gender":"Female",
        "favorite_brand":"Nike",
        "postcode": "10560",
        "address_line": "1 Gifted Way",
        "address_line2": "",
        "apartment_suite_number": "",
        "town_city": "Salem Center",
        "state": "NY",
        "delivery_instructions": "",
    },{
        "id": "3334476998",
        "email": "jblazing@blazemail.com",
        "password": 'justBlaze$100',
        "first_name":"Johnny",
        "middle_name":"",
        "last_name":"Blaze",
        "mobile_phone":"213-909-8763",
        "mobile_notification":"True",
        "shoe_size":"10",
        "size_gender":"Male",
        "favorite_brand":"Nike",
        "postcode": "90015",
        "address_line": "1112 S Figueroa St",
        "address_line2": "",
        "apartment_suite_number": "",
        "town_city": "Los Angeles",
        "state": "CA",
        "delivery_instructions": "",
    },{
        "id": "3333000990",
        "email": "CBarton@avengers.com",
        "password": 'spotonDtarget0^',
        "first_name":"Clinton",
        "middle_name":"F",
        "last_name":"Barton",
        "mobile_phone":"713-635-2123",
        "mobile_notification":"True",
        "shoe_size":"8",
        "size_gender":"Male",
        "favorite_brand":"Puma",
        "postcode": "77002",
        "address_line": "1515 Polk St",
        "address_line2": "",
        "apartment_suite_number": "14B",
        "town_city": "Houston",
        "state": "TX",
        "delivery_instructions": "",
    },{
        "id": "009911224321",
        "email": "echolopez@gmail.com",
        "password": 'kickA$$99',
        "first_name":"Maya",
        "middle_name":"",
        "last_name":"Lopez",
        "mobile_phone":"580-374-6431",
        "mobile_notification":"True",
        "shoe_size":"5",
        "size_gender":"Female",
        "favorite_brand":"Timberland",
        "postcode": "74701",
        "address_line": "1606 Chukka Hina",
        "address_line2": "",
        "apartment_suite_number": "",
        "town_city": "Durant",
        "state": "OK",
        "delivery_instructions": "",
    },{
        "id": "009911223366",
        "email": "mspector@newmail.com",
        "password": 'byTheM00n#',
        "first_name":"Marc",
        "middle_name":"",
        "last_name":"Spector",
        "mobile_phone":"323-434-8743",
        "mobile_notification":"True",
        "shoe_size":"9",
        "size_gender":"Male",
        "favorite_brand":"Nike",
        "postcode": "90303",
        "address_line": "3930 W Century Blvd",
        "address_line2": "",
        "apartment_suite_number": "3A",
        "town_city": "Inglewood",
        "state": "CA",
        "delivery_instructions": "",
    },
    {
        "id": "00957323366",
        "email": "bbanner@avengers.com",
        "password": 'gammaGeek*33',
        "first_name":"Bruce",
        "middle_name":"",
        "last_name":"Banner",
        "mobile_phone":"206-808-0102",
        "mobile_notification":"True",
        "shoe_size":"16.5",
        "size_gender":"Male",
        "favorite_brand":"Adidas",
        "postcode": "98109",
        "address_line": "305 Harrison St",
        "address_line2": "",
        "apartment_suite_number": "",
        "town_city": "Seattle",
        "state": "WA",
        "delivery_instructions": "",
    },
     {
        "id": "02937621336",
        "email": "bwayne@wayneenterprise.com",
        "password": 'batsInA!1Black',
        "first_name":"Bruce",
        "middle_name":"",
        "last_name":"Wayne",
        "mobile_phone":"212-443-2983",
        "mobile_notification":"True",
        "shoe_size":"10.5",
        "size_gender":"Male",
        "favorite_brand":"Nike",
        "postcode": "11005",
        "address_line": "1 Wayne Place",
        "address_line2": "",
        "apartment_suite_number": "",
        "town_city": "Gotham",
        "state": "NY",
        "delivery_instructions": "",
    },
    {
        "id": "13957721339",
        "email": "ckent@justiceleague.com",
        "password": '$onOfKrypton!',
        "first_name":"Clark",
        "middle_name":"",
        "last_name":"Kent",
        "mobile_phone":"312-334-9238",
        "mobile_notification":"True",
        "shoe_size":"10.5",
        "size_gender":"Male",
        "favorite_brand":"Puma",
        "postcode": "60054",
        "address_line": "311 W Illinois St.",
        "address_line2": "",
        "apartment_suite_number": "12G",
        "town_city": "Metropolis",
        "state": "IL",
        "delivery_instructions": "",
    },
    {
        "id": "100001020304240",
        "email": "dgrayson@justiceleague.com",
        "password": 'robinToKnight1$',
        "first_name":"Dick",
        "middle_name":"",
        "last_name":"Grayson",
        "mobile_phone":"212-443-2988",
        "mobile_notification":"True",
        "shoe_size":"9",
        "size_gender":"Male",
        "favorite_brand":"Converse",
        "postcode": "11005",
        "address_line": "100 Downey St",
        "address_line2": "",
        "apartment_suite_number": "7A",
        "town_city": "Gotham",
        "state": "NY",
        "delivery_instructions": "",
    },
]
