"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(_('email address'), unique=True, db_index=True)
    first_name = models.CharField(max_length=50, blank=True)
    middle_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    mobile_phone = models.CharField(max_length=20, blank=True)
    mobile_notification = models.BooleanField(default=False)
    shoe_size = models.CharField(max_length=6)
    size_gender = models.CharField(choices=SIZE_BY_GENDER, default='male', max_length=200)
    favorite_brand = models.CharField(max_length=100, choices=BRAND_CHOICES, default='nike')
    deleted_at = models.DateTimeField(null=True, blank=True)  

    // Address
    postcode = models.CharField(_("Postcode"), max_length=50)
    address_line = models.CharField(_("Address Line 1"), max_length=255)
    address_line2 = models.CharField(_("Address Line 2"), max_length=255, blank=True)
    apartment_suite_number = models.CharField(_("Apartment/Suite"), max_length=50)
    town_city = models.CharField(_("Town/City/State"), max_length=150)
    state  = models.CharField(_("State"), max_length=100)
    delivery_instructions = models.TextField(_("Deliver Instructions"))
"""

test_account_data = [
    {
        "id": "0123232445",
        "email": "peterparker@avengers.com",
        "first_name":"Peter",
        "middle_name":"",
        "last_name":"Parker",
        "mobile_phone":"851-237-4564",
        "mobile_notification":"True",
        "shoe_size":"8.5",
        "size_gender":"Male",
        "favorite_brand":"Nike",
        "postcode": "11431",
        "address_line": "2131 Wooster Ave",
        "address_line2": "",
        "apartment_suite_number": "13G",
        "town_city": "Sunnyside",
        "state": "NY",
        "delivery_instructions": "",
   },
   {
        "id": "1132343477",
        "email": "Lhowlett@gmail.com",
        "first_name":"Logan",
        "middle_name":"W",
        "last_name":"Howlett",
        "mobile_phone":"518-321-0921",
        "mobile_notification":"True",
        "shoe_size":"9",
        "size_gender":"Male",
        "favorite_brand":"Puma",
        "postcode": "10560",
        "address_line": "1 Gifted Way",
        "address_line2": "",
        "apartment_suite_number": "",
        "town_city": "Salem Center",
        "state": "NY",
        "delivery_instructions": "",
   },
   {
        "id": "0987609876",
        "email": "srodgers@avengers.com",
        "first_name":"Steve",
        "middle_name":"G",
        "last_name":"Rodgers",
        "mobile_phone":"718-434-2211",
        "mobile_notification":"True",
        "shoe_size":"11.5",
        "size_gender":"Male",
        "favorite_brand":"Adidas",
        "postcode": "11228",
        "address_line": "1899 72nd Street",
        "address_line2": "",
        "apartment_suite_number": "First Floor",
        "town_city": "Bensonhurst",
        "state": "NY",
        "delivery_instructions": "",
   },
   {
        "id": "1231234567",
        "email": "tstark@avengers.com",
        "first_name":"Anthony",
        "middle_name":"Edward",
        "last_name":"Stark",
        "mobile_phone":"212-345-3212",
        "mobile_notification":"True",
        "shoe_size":"10",
        "size_gender":"Male",
        "favorite_brand":"Gucci",
        "postcode": "11221",
        "address_line": "13 Park Ave",
        "address_line2": "",
        "apartment_suite_number": "PH",
        "town_city": "New York",
        "state": "NY",
        "delivery_instructions": "",
   },
   {
       "id": "5436577001",
        "email": "JCJones@aol.com",
        "first_name":"Jessica",
        "middle_name":"C",
        "last_name":"Jones",
        "mobile_phone":"212-221-8453",
        "mobile_notification":"True",
        "shoe_size":"6",
        "size_gender":"Female",
        "favorite_brand":"Asics",
        "postcode": "10027",
        "address_line": "280 W 127th St",
        "address_line2": "",
        "apartment_suite_number": "7G",
        "town_city": "New York",
        "state": "NY",
        "delivery_instructions": "",
   },
   {
       {
        "id": "0009998876",
        "email": "",
        "first_name":"Anna Marie",
        "middle_name":"",
        "last_name":"LeBeau",
        "mobile_phone":"212-443-2145",
        "mobile_notification":"True",
        "shoe_size":"5",
        "size_gender":"Female",
        "favorite_brand":"Nike",
        "postcode": "10560",
        "address_line": "1 Gifted Way",
        "address_line2": "",
        "apartment_suite_number": "",
        "town_city": "Salem Center",
        "state": "NY",
        "delivery_instructions": "",
    },
   }
    
]

"""
{

    
    {
        "id": "3334476998",
        "email": "",
        "first_name":"",
        "middle_name":"",
        "last_name":"",
        "mobile_phone":"",
        "mobile_notification":"",
        "shoe_size":"",
        "size_gender":"",
        "favorite_brand":"",
         "postcode": "",
        "address_line": "",
        "address_line2": "",
        "apartment_suite_number": "",
        "town_city": "",
        "state": "NY",
        "delivery_instructions": "",
    },
    {
        "id": "3333000990",
        "email": "",
        "first_name":"",
        "middle_name":"",
        "last_name":"",
        "mobile_phone":"",
        "mobile_notification":"",
        "shoe_size":"",
        "size_gender":"",
        "favorite_brand":"",
         "postcode": "",
        "address_line": "",
        "address_line2": "",
        "apartment_suite_number": "",
        "town_city": "",
        "state": "NY",
        "delivery_instructions": "",
    },
    {
        "id": "009911223366",
        "email": "",
        "first_name":"",
        "middle_name":"",
        "last_name":"",
        "mobile_phone":"",
        "mobile_notification":"",
        "shoe_size":"",
        "size_gender":"",
        "favorite_brand":"",
         "postcode": "",
        "address_line": "",
        "address_line2": "",
        "apartment_suite_number": "",
        "town_city": "",
        "state": "NY",
        "delivery_instructions": "",
    },
    {
        "id": "00957323366",
        "email": "",
        "first_name":"",
        "middle_name":"",
        "last_name":"",
        "mobile_phone":"",
        "mobile_notification":"",
        "shoe_size":"",
        "size_gender":"",
        "favorite_brand":"",
         "postcode": "",
        "address_line": "",
        "address_line2": "",
        "apartment_suite_number": "",
        "town_city": "",
        "state": "NY",
        "delivery_instructions": "",
    },
    {
        "id": "009911224321",
        "email": "",
        "first_name":"",
        "middle_name":"",
        "last_name":"",
        "mobile_phone":"",
        "mobile_notification":"",
        "shoe_size":"",
        "size_gender":"",
        "favorite_brand":"",
         "postcode": "",
        "address_line": "",
        "address_line2": "",
        "apartment_suite_number": "",
        "town_city": "",
        "state": "NY",
        "delivery_instructions": "",
    },
"""