# Generated by Django 5.2.4 on 2025-08-04 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pop_up_order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('n/a', 'N/A'), ('usps', 'USPS'), ('ups', 'UPS'), ('FedEx', 'FedEx')], default='n/a', max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('cancelled', 'Cancelled'), ('in_dispute', 'In Dispute'), ('pending', 'Pending'), ('shipped', 'Shipped'), ('returned', 'Returned'), ('delivered', 'Delivered')], default='pending', max_length=50)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='pop_up_order.popupcustomerorder')),
            ],
            options={
                'verbose_name': 'PopUp Shipment',
                'verbose_name_plural': 'PopUp Shipments',
            },
        ),
    ]
