# Generated by Django 5.1.3 on 2025-07-09 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_popupcustomerorder_options_and_more'),
        ('pop_up_shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('usps', 'USPS'), ('ups', 'UPS'), ('FedEx', 'FedEx')], default='usps', max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('in_dispute', 'In Dispute')], default='pending', max_length=50)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.popupcustomerorder')),
            ],
            options={
                'verbose_name': 'PopUp Shipment',
                'verbose_name_plural': 'PopUp Shipments',
            },
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
