# Generated by Django 5.1.3 on 2025-07-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_shipping', '0002_popupshipment_delete_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupshipment',
            name='carrier',
            field=models.CharField(choices=[('n/a', 'N/A'), ('usps', 'USPS'), ('ups', 'UPS'), ('FedEx', 'FedEx')], default='n/a', max_length=50),
        ),
        migrations.AlterField(
            model_name='popupshipment',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('in_dispute', 'In Dispute'), ('pending', 'Pending'), ('shipped', 'Shipped'), ('returned', 'Returned'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
    ]
