# Generated by Django 5.1.3 on 2025-07-04 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_popupcustomerorder_options_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('in_review', 'In Review'), ('disputed', 'Disputed'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('suspicious_flagged', models.BooleanField(default=False)),
                ('notified_ready_to_ship', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.popupcustomerorder')),
            ],
            options={
                'verbose_name': 'PopUp Payment',
                'verbose_name_plural': 'PopUp Payments',
                'ordering': ('-created_at',),
            },
        ),
    ]
