# Generated by Django 5.1.3 on 2025-07-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_popuppayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='popuppayment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('venmo', 'Venmo'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay')], default='stripe', max_length=20),
            preserve_default=False,
        ),
    ]
