# Generated by Django 5.2.4 on 2025-08-04 22:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_winning_bid', models.BooleanField(default=False)),
                ('max_auto_bid', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum bid limit for automatic bidding.', max_digits=10, null=True)),
                ('bid_increment', models.DecimalField(decimal_places=2, default=5.0, help_text='Minimum amount by which the next bid must increase.', max_digits=10)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Bid expiration time.', null=True)),
            ],
            options={
                'verbose_name': 'PopUpBid',
                'verbose_name_plural': 'PopUpBids',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PopUpCustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Miss', 'Miss'), ('Dr', 'Dr.'), ('Prof', 'Prof.')], default='', max_length=10, null=True)),
                ('suffix', models.CharField(blank=True, choices=[('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('CPA', 'CPA'), ('M.D.', 'M.D.'), ('PhD', 'PhD')], default='', max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('postcode', models.CharField(max_length=50, verbose_name='Postcode')),
                ('address_line', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('apartment_suite_number', models.CharField(blank=True, max_length=50, verbose_name='Apartment/Suite')),
                ('town_city', models.CharField(max_length=150, verbose_name='Town/City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('delivery_instructions', models.TextField(blank=True, verbose_name='Deliver Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('is_default_shipping', models.BooleanField(default=False)),
                ('is_default_billing', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PopUpCustomerAddress',
                'verbose_name_plural': 'PopUpCustomerAddresses',
            },
        ),
        migrations.CreateModel(
            name='PopUpCustomerIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PopUp Customer IP Address',
                'verbose_name_plural': 'PopUp Customer IP Addresses',
            },
        ),
        migrations.CreateModel(
            name='PopUpCustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_billing_agreement_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopUpPasswordResetRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PopUp Password Reset Request Log',
                'verbose_name_plural': 'PopUp Password Reset Request Logs',
            },
        ),
        migrations.CreateModel(
            name='PopUpPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_api', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PopUp Customer Purchase',
                'verbose_name_plural': 'PopUp Customer PopUp Purchases',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='PopUpCustomer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('mobile_phone', models.CharField(blank=True, max_length=20)),
                ('mobile_notification', models.BooleanField(default=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=40, null=True)),
                ('shoe_size', models.CharField(max_length=10)),
                ('size_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=200)),
                ('favorite_brand', models.CharField(choices=[('adidas', 'Adidas'), ('Asics', 'asics'), ('balenciaga', 'Balenciaga'), ('brooks', 'Brooks'), ('fear_of_god ', 'Fear of God'), ('gucci', 'Gucci'), ('jordan', 'Jordan'), ('new_balance', 'New Balance'), ('nike', 'Nike'), ('prada', 'Prada'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('saucony', 'Saucony'), ('yeezy', 'Yeezy')], default='nike', max_length=100)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_password_reset', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'PopUpCustomer',
                'verbose_name_plural': 'PopUpCustomers',
            },
        ),
    ]
