# Generated by Django 5.1.3 on 2025-12-01 13:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_middle_name'),
        ('pop_up_auction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpCustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefix', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Miss', 'Miss'), ('Dr', 'Dr.'), ('Prof', 'Prof.')], default='', max_length=10, null=True)),
                ('suffix', models.CharField(blank=True, choices=[('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('CPA', 'CPA'), ('M.D.', 'M.D.'), ('PhD', 'PhD')], default='', max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('postcode', models.CharField(max_length=50, verbose_name='Postcode')),
                ('address_line', models.CharField(max_length=255, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, verbose_name='Address Line 2')),
                ('apartment_suite_number', models.CharField(blank=True, max_length=50, verbose_name='Apartment/Suite')),
                ('town_city', models.CharField(max_length=150, verbose_name='Town/City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('delivery_instructions', models.TextField(blank=True, verbose_name='Deliver Instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('is_default_shipping', models.BooleanField(default=False)),
                ('is_default_billing', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'PopUpCustomerAddress',
                'verbose_name_plural': 'PopUpCustomerAddresses',
            },
        ),
        migrations.CreateModel(
            name='PopUpCustomerIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PopUp Customer IP Address',
                'verbose_name_plural': 'PopUp Customer IP Addresses',
            },
        ),
        migrations.CreateModel(
            name='PopUpCustomerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('shoe_size', models.CharField(blank=True, max_length=10, null=True)),
                ('size_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=200, null=True)),
                ('favorite_brand', models.CharField(choices=[('adidas', 'Adidas'), ('asics', 'Asics'), ('balenciaga', 'Balenciaga'), ('brooks', 'Brooks'), ('fear_of_god ', 'Fear of God'), ('gucci', 'Gucci'), ('jordan', 'Jordan'), ('new_balance', 'New Balance'), ('nike', 'Nike'), ('prada', 'Prada'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('saucony', 'Saucony'), ('yeezy', 'Yeezy')], default='nike', max_length=100)),
                ('prods_interested_in', models.ManyToManyField(blank=True, related_name='interested_users', to='pop_up_auction.popupproduct')),
                ('prods_on_notice_for', models.ManyToManyField(blank=True, related_name='notified_users', to='pop_up_auction.popupproduct')),
            ],
            options={
                'verbose_name': 'PopUpCustomerProfile',
                'verbose_name_plural': 'PopUpCustomerProfiles',
            },
        ),
        migrations.CreateModel(
            name='PopUpCustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_billing_agreement_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='pop_accounts.popupcustomerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PopUpBid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_winning_bid', models.BooleanField(default=False)),
                ('max_auto_bid', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum bid limit for automatic bidding.', max_digits=10, null=True)),
                ('bid_increment', models.DecimalField(decimal_places=2, default=5.0, help_text='Minimum amount by which the next bid must increase.', max_digits=10)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Bid expiration time.', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='pop_up_auction.popupproduct')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='pop_accounts.popupcustomerprofile')),
            ],
            options={
                'verbose_name': 'PopUpBid',
                'verbose_name_plural': 'PopUpBids',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PopUpPasswordResetRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PopUp Password Reset Request Log',
                'verbose_name_plural': 'PopUp Password Reset Request Logs',
            },
        ),
        migrations.CreateModel(
            name='PopUpPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_api', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pop_accounts.popupcustomeraddress')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pop_accounts.popupbid')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='pop_accounts.popupcustomerprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='pop_up_auction.popupproduct')),
            ],
            options={
                'verbose_name': 'PopUp Customer Purchase',
                'verbose_name_plural': 'PopUp Customer PopUp Purchases',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
