# Generated by Django 5.1.3 on 2025-12-31 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popupbid',
            options={'ordering': ['-timestamp'], 'verbose_name': 'PopUp Bid', 'verbose_name_plural': 'PopUp Bids'},
        ),
        migrations.AlterModelOptions(
            name='popupcustomeraddress',
            options={'verbose_name': 'PopUp Customer Address', 'verbose_name_plural': 'PopUp Customer Addresses'},
        ),
        migrations.AlterModelOptions(
            name='popupcustomerprofile',
            options={'verbose_name': 'PopUp Customer Profile', 'verbose_name_plural': 'PopUp Customer Profiles'},
        ),
        migrations.AlterField(
            model_name='popupbid',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bids', to='pop_accounts.popupcustomerprofile'),
        ),
    ]
