# Generated by Django 5.1.3 on 2025-03-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popupcustomer',
            old_name='size',
            new_name='shoe_size',
        ),
        migrations.RemoveField(
            model_name='popupcustomer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='popupcustomeraddress',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='popupcustomeraddress',
            name='phone',
        ),
        migrations.AddField(
            model_name='popupcustomeraddress',
            name='state',
            field=models.CharField(default='NY', max_length=100, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='popupcustomer',
            name='favorite_brand',
            field=models.CharField(choices=[('adidas', 'Adidas'), ('asics', 'Asics'), ('balenciaga', 'Balenciaga'), ('brooks', 'Brooks'), ('fear_of_god ', 'Fear of God'), ('gucci', 'Gucci'), ('jordan', 'Jordan'), ('new_balance', 'New Balance'), ('nike', 'Nike'), ('prada', 'Prada'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('saucony', 'Saucony'), ('yeezy', 'Yeezy')], default='nike', max_length=100),
        ),
        migrations.AlterField(
            model_name='popupcustomeraddress',
            name='town_city',
            field=models.CharField(max_length=150, verbose_name='Town/City'),
        ),
    ]
