# Generated by Django 5.2.4 on 2025-08-04 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pop_accounts', '0001_initial'),
        ('pop_up_auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupcustomer',
            name='prods_interested_in',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='pop_up_auction.popupproduct'),
        ),
        migrations.AddField(
            model_name='popupcustomer',
            name='prods_on_notice_for',
            field=models.ManyToManyField(blank=True, related_name='notified_users', to='pop_up_auction.popupproduct'),
        ),
        migrations.AddField(
            model_name='popupcustomer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='popupbid',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popupbid',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='pop_up_auction.popupproduct'),
        ),
        migrations.AddField(
            model_name='popupcustomeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='popupcustomerip',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popupcustomerpayment',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popuppasswordresetrequestlog',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popuppurchase',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pop_accounts.popupcustomeraddress'),
        ),
        migrations.AddField(
            model_name='popuppurchase',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pop_accounts.popupbid'),
        ),
        migrations.AddField(
            model_name='popuppurchase',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popuppurchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='pop_up_auction.popupproduct'),
        ),
    ]
