# Generated by Django 5.1.3 on 2025-05-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_accounts', '0003_alter_popupcustomer_favorite_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupcustomer',
            name='favorite_brand',
            field=models.CharField(choices=[('adidas', 'Adidas'), ('asics', 'Asics'), ('balenciaga', 'Balenciaga'), ('brooks', 'Brooks'), ('fear_of_god ', 'Fear of God'), ('gucci', 'Gucci'), ('jordan', 'Jordan'), ('new_balance', 'New Balance'), ('nike', 'Nike'), ('prada', 'Prada'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('saucony', 'Saucony'), ('yeezy', 'Yeezy')], default='nike', max_length=100),
        ),
        migrations.AlterField(
            model_name='popupcustomeraddress',
            name='prefix',
            field=models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('miss', 'Miss.'), ('dr', 'Dr.'), ('prof', 'Prof.'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='popupcustomeraddress',
            name='suffix',
            field=models.CharField(choices=[('jr', 'Jr.'), ('sr', 'Sr.'), ('ii', 'II'), ('iii', 'III'), ('iv', 'IV'), ('CPA', 'CPA'), ('M.D.', 'M.D.'), ('PhD', 'PhD.'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
