# Generated by Django 5.1.3 on 2025-04-30 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_accounts', '0005_alter_popupcustomer_favorite_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupcustomer',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='popupcustomer',
            name='favorite_brand',
            field=models.CharField(choices=[('adidas', 'Adidas'), ('asics', 'Asics'), ('balenciaga', 'Balenciaga'), ('brooks', 'Brooks'), ('fear_of_god ', 'Fear of God'), ('gucci', 'Gucci'), ('jordan', 'Jordan'), ('new_balance', 'New Balance'), ('nike', 'Nike'), ('prada', 'Prada'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('saucony', 'Saucony'), ('yeezy', 'Yeezy')], default='nike', max_length=100),
        ),
        migrations.CreateModel(
            name='PasswordResetRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
