# Generated by Django 5.1.3 on 2025-05-10 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop_accounts', '0006_popupcustomer_last_password_reset_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordResetRequestLog',
            new_name='PopUpPasswordResetRequestLog',
        ),
    ]
