# Generated by Django 5.2.4 on 2025-08-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_accounts', '0006_alter_popupcustomer_favorite_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupcustomer',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='popupcustomer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='popupcustomer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='popupcustomer',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='popupcustomer',
            name='shoe_size',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='popupcustomer',
            name='size_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=200, null=True),
        ),
    ]
