# Generated by Django 5.1.3 on 2025-05-11 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_accounts', '0007_rename_passwordresetrequestlog_popuppasswordresetrequestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupcustomer',
            name='favorite_brand',
            field=models.CharField(choices=[('adidas', 'Adidas'), ('Asics', 'asics'), ('balenciaga', 'Balenciaga'), ('brooks', 'Brooks'), ('fear_of_god ', 'Fear of God'), ('gucci', 'Gucci'), ('jordan', 'Jordan'), ('new_balance', 'New Balance'), ('nike', 'Nike'), ('prada', 'Prada'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('saucony', 'Saucony'), ('yeezy', 'Yeezy')], default='nike', max_length=100),
        ),
        migrations.AlterField(
            model_name='popupcustomeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
    ]
