# Generated by Django 5.2.4 on 2025-11-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_accounts', '0008_alter_popupcustomer_favorite_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupcustomerip',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='popupcustomerip',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
