# Generated by Django 5.1.3 on 2025-05-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop_accounts', '0010_alter_popuppasswordresetrequestlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popupcustomer',
            name='past_purchases',
        ),
    ]
