# Generated by Django 5.1.3 on 2025-06-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_accounts', '0013_alter_popupcustomer_favorite_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popupcustomerip',
            options={'verbose_name': 'PopUp Customer IP Address', 'verbose_name_plural': 'PopUp Customer IP Addresses'},
        ),
        migrations.AlterModelOptions(
            name='popuppasswordresetrequestlog',
            options={'verbose_name': 'PopUp Password Reset Request Log', 'verbose_name_plural': 'PopUp Password Reset Request Logs'},
        ),
        migrations.AlterModelOptions(
            name='popuppurchase',
            options={'ordering': ['-purchased_at'], 'verbose_name': 'PopUp Customer Purchase', 'verbose_name_plural': 'PopUp Customer PopUp Purchases'},
        ),
        migrations.AlterField(
            model_name='popupcustomer',
            name='favorite_brand',
            field=models.CharField(choices=[('adidas', 'Adidas'), ('asics', 'Asics'), ('balenciaga', 'Balenciaga'), ('brooks', 'Brooks'), ('fear_of_god ', 'Fear of God'), ('gucci', 'Gucci'), ('jordan', 'Jordan'), ('new_balance', 'New Balance'), ('nike', 'Nike'), ('prada', 'Prada'), ('puma', 'Puma'), ('reebok', 'Reebok'), ('saucony', 'Saucony'), ('yeezy', 'Yeezy')], default='nike', max_length=100),
        ),
    ]
