# Generated by Django 5.1.3 on 2025-12-31 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popupcoupon',
            options={'verbose_name': 'PopUp Coupon', 'verbose_name_plural': 'PopUp Coupons'},
        ),
        migrations.AlterModelOptions(
            name='popupreferral',
            options={'verbose_name': 'PopUp Referral', 'verbose_name_plural': 'PopUp Referrals'},
        ),
    ]
