# Generated by Django 5.1.3 on 2025-03-07 03:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_year', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('auction_start_date', models.DateTimeField(blank=True, null=True)),
                ('auction_end_date', models.DateTimeField(blank=True, null=True)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('product_sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], default='male', max_length=100)),
                ('product_type', models.CharField(choices=[('shoe', 'Shoe'), ('clothing', 'Clothing'), ('miscellaneous', 'Miscellaneous'), ('memorabilia', 'Memorabilia')], default='shoe', max_length=100)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('style_number', models.CharField(blank=True, max_length=100, null=True)),
                ('colorway', models.CharField(blank=True, max_length=100, null=True)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory_status', models.CharField(choices=[('anticipated', 'Anticipated'), ('in_transit', 'In Transit'), ('in_inventory', 'In Inventory')], default='anticipated', max_length=30)),
            ],
            options={
                'ordering': ['release_date'],
            },
        ),
        migrations.CreateModel(
            name='PopUpProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_category', models.CharField(choices=[('shoe', 'Shoe Size'), ('clothing', 'Clothing Size')], max_length=20)),
                ('size_value', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='auction.popupproducts')),
            ],
        ),
    ]
