# Generated by Django 5.1.3 on 2025-04-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupproducttype',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
