# Generated by Django 5.1.3 on 2025-04-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_popupproducttype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupproduct',
            name='secondary_product_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='secondary_name'),
        ),
        migrations.AlterField(
            model_name='popupproduct',
            name='product_title',
            field=models.CharField(help_text='Required', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='popupproducttype',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
