# Generated by Django 5.1.3 on 2025-06-21 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auction_winnerreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popupproduct',
            name='starting_price',
        ),
        migrations.AddField(
            model_name='popupproduct',
            name='auction_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='popupproduct',
            name='bought_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='popupproduct',
            name='buy_now_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='popupproduct',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auction', to=settings.AUTH_USER_MODEL),
        ),
    ]
