# Generated by Django 5.1.3 on 2025-04-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_popupproduct_secondary_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupproduct',
            name='current_highest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stores the current highest bid for this product.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='popupproduct',
            name='inventory_status',
            field=models.CharField(choices=[('anticipated', 'Anticipated'), ('in_transit', 'In Transit'), ('in_inventory', 'In Inventory'), ('sold_out', 'Sold Out')], default='anticipated', max_length=30),
        ),
    ]
