# Generated by Django 5.1.3 on 2025-06-21 09:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_remove_popupproduct_starting_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='winnerreservation',
            unique_together={('product', 'user')},
        ),
        migrations.RemoveField(
            model_name='winnerreservation',
            name='auction',
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
