# Generated by Django 5.1.3 on 2025-06-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_popupproduct_buy_now_end_popupproduct_buy_now_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupproduct',
            name='inventory_status',
            field=models.CharField(choices=[('anticipated', 'Anticipated'), ('in_transit', 'In Transit'), ('in_inventory', 'In Inventory'), ('reserved', 'Reserved'), ('sold_out', 'Sold Out')], default='anticipated', max_length=30),
        ),
    ]
