# Generated by Django 5.1.3 on 2025-06-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_alter_popupproduct_inventory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupproduct',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
