# Generated by Django 5.1.3 on 2025-06-28 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_popupproduct_reserved_until'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popupproduct',
            options={'ordering': ('-created_at',), 'verbose_name': 'PopUp Product', 'verbose_name_plural': 'PopUp Products'},
        ),
        migrations.AlterModelOptions(
            name='popupproductimage',
            options={'verbose_name': 'PopUp Product Image', 'verbose_name_plural': 'PopUp Product Images'},
        ),
        migrations.AlterModelOptions(
            name='popupproductspecification',
            options={'verbose_name': 'PopUp Product Specification', 'verbose_name_plural': 'PopUp Product Specifications'},
        ),
        migrations.AlterModelOptions(
            name='popupproductspecificationvalue',
            options={'verbose_name': 'PopUp Product Specification Value', 'verbose_name_plural': 'PopUp Product Specification Values'},
        ),
        migrations.AlterModelOptions(
            name='popupproducttype',
            options={'verbose_name': 'PopUp Product Type', 'verbose_name_plural': 'PopUp Product Types'},
        ),
    ]
