# Generated by Django 5.1.3 on 2025-06-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_alter_popupproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='winnerreservation',
            name='reminder_1hr_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='winnerreservation',
            name='reminder_24hr_sent',
            field=models.BooleanField(default=False),
        ),
    ]
