# Generated by Django 5.1.3 on 2025-07-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_winnerreservation_reminder_1hr_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupproduct',
            name='product_weight_lbs',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in pounds for shipping calculation', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='popupproduct',
            name='zip_code_stored',
            field=models.CharField(blank=True, help_text='ZIP code of the storage or fulfillment location', max_length=10, null=True),
        ),
    ]
