# Generated by Django 5.1.3 on 2025-07-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_popupproduct_product_weight_lbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupproductimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Paste the URL of the image (e.g. S3, Cloudinary)', null=True, verbose_name='External Image URL'),
        ),
    ]
