# Generated by Django 5.1.3 on 2025-07-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_popupproductimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupproductimage',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', help_text='Upload a product image', null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
