# Generated by Django 5.1.3 on 2025-07-09 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auction', '0010_popupproduct_product_weight_lbs_and_more'),
        ('orders', '0009_alter_popupcustomerorder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUpFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('is_disputed', models.BooleanField(default=False)),
                ('is_refunded', models.BooleanField(default=False)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.popupcustomerorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.popupproduct')),
            ],
        ),
    ]
