# Generated by Django 5.1.3 on 2026-06-21 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_finance', '0001_initial'),
        ('pop_up_order', '0003_alter_popuporderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupfinance',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_records', to='pop_up_order.popupcustomerorder'),
        ),
    ]
