# Generated by Django 5.1.3 on 2025-07-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popupfinance',
            options={'verbose_name': 'PopUp Finance', 'verbose_name_plural': 'PopUp Finances'},
        ),
    ]
