# Generated by Django 5.2.4 on 2025-08-04 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pop_up_auction', '0001_initial'),
        ('pop_up_finance', '0001_initial'),
        ('pop_up_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupfinance',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pop_up_order.popupcustomerorder'),
        ),
        migrations.AddField(
            model_name='popupfinance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pop_up_auction.popupproduct'),
        ),
    ]
