# Generated by Django 5.1.3 on 2026-06-14 19:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_bot', '0004_dailyhealthcheck_healthchecknotification_and_more'),
        ('pop_up_cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementCartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=15.0, help_text='Service fee charged to user (snapshot at time of cart add)', max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('procurement_service_request', models.OneToOneField(help_text='The procurement request this fee covers', on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='pop_up_bot.procurementservicerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procurement Cart Item',
                'verbose_name_plural': 'Procurement Cart Items',
            },
        ),
    ]
