# Generated by Django 5.1.3 on 2026-06-07 17:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_bot', '0003_procurementexecution_error_type'),
        ('pop_up_payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('venmo', 'Venmo')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Stripe PaymentIntent ID, PayPal transaction ID, or Braintree transaction ID', max_length=255, null=True)),
                ('refund_reference', models.CharField(blank=True, help_text='Refund transaction ID from payment processor', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if payment failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_payment', to='pop_up_bot.procurementservicerequest')),
            ],
            options={
                'verbose_name': 'Service Payment',
                'verbose_name_plural': 'Service Payments',
                'ordering': ('-created_at',),
            },
        ),
    ]
