# Generated by Django 5.1.3 on 2026-06-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_payment', '0002_servicepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepayment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
