# Generated by Django 5.1.3 on 2026-05-26 21:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pop_up_auction', '0002_popupproduct_pop_up_auct_product_9b7d5f_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(db_index=True, help_text="Site identifier (e.g., 'nike', 'footlocker')", max_length=50)),
                ('name', models.CharField(help_text='Cookie name', max_length=255)),
                ('value', models.TextField(help_text='Cookie value')),
                ('domain', models.CharField(help_text="Cookie domain (e.g., '.nike.com')", max_length=255)),
                ('path', models.CharField(default='/', help_text='Cookie path', max_length=255)),
                ('expires', models.DateTimeField(blank=True, help_text='Cookie expiration time', null=True)),
                ('http_only', models.BooleanField(default=False, help_text='Cookie httpOnly flag')),
                ('secure', models.BooleanField(default=False, help_text='Cookie secure flag (HTTPS only)')),
                ('same_site', models.CharField(choices=[('Lax', 'Lax'), ('Strict', 'Strict'), ('None', 'None')], default='Lax', help_text='Cookie SameSite flag', max_length=10)),
                ('saved_at', models.DateTimeField(auto_now_add=True, help_text='When this cookie was saved')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this cookie was last updated')),
            ],
            options={
                'verbose_name': 'Bot Cookie',
                'verbose_name_plural': 'Bot Cookies',
                'db_table': 'pop_up_bot_cookies',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['site_name', 'name'], name='pop_up_bot__site_na_24341c_idx'), models.Index(fields=['site_name', '-updated_at'], name='pop_up_bot__site_na_eb8921_idx'), models.Index(fields=['expires'], name='pop_up_bot__expires_60b519_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_name', 'domain', 'name'), name='unique_site_domain_cookie_name')],
            },
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text="Name of product to find (e.g., 'Air Jordan 1')", max_length=255)),
                ('target_size', models.CharField(help_text="Size to find (e.g., 'US 10')", max_length=50)),
                ('target_color', models.CharField(blank=True, help_text='Optional color preference', max_length=100, null=True)),
                ('max_price', models.DecimalField(decimal_places=2, help_text='Maximum price willing to pay', max_digits=10)),
                ('procurement_type', models.CharField(choices=[('inventory', 'Inventory Procurement'), ('concierge', 'Concierge Procurement')], default='inventory', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('priority_score', models.IntegerField(default=0, help_text='Higher = more urgent')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Procurement request expires at this time', null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, help_text='When the item was successfully procured', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pop_up_auction.popupbrand')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pop_up_auction.popupproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procurement Request',
                'verbose_name_plural': 'Procurement Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('strategy_used', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel'), ('priority', 'Priority'), ('fastest', 'Fastest'), ('cheapest', 'Cheapest'), ('retail_only', 'Retail Only')], default='sequential', help_text='Which procurement strategy was used', max_length=20)),
                ('winning_site', models.CharField(blank=True, help_text='Which site successfully procured the item', max_length=50, null=True)),
                ('order_id', models.CharField(blank=True, help_text='Order ID from the site', max_length=255, null=True, unique=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price paid for the item', max_digits=10, null=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, help_text='Prevents duplicate execution')),
                ('started_at', models.DateTimeField(help_text='When execution started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When execution completed (success or failure)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed', null=True)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID if running asynchronously', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('procurement_request', models.ForeignKey(help_text='The request this execution is fulfilling', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='pop_up_bot.procurementrequest')),
            ],
            options={
                'verbose_name': 'Procurement Execution',
                'verbose_name_plural': 'Procurement Executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(db_index=True, help_text='Which site this attempt targeted', max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('product_found', 'Product Found'), ('carted', 'Carted'), ('checkout_started', 'Checkout Started'), ('payment_submitted', 'Payment Submitted'), ('success', 'Success'), ('failed', 'Failed'), ('oos', 'Out Of Stock'), ('blocked', 'Blocked')], db_index=True, default='started', max_length=50)),
                ('failure_reason', models.CharField(blank=True, choices=[('oos', 'Out Of Stock'), ('payment_declined', 'Payment Declined'), ('captcha', 'Captcha'), ('site_timeout', 'Site Timeout'), ('blocked', 'Blocked'), ('selector_failure', 'Selector Failure'), ('network_error', 'Network Error'), ('unknown', 'Unknown')], help_text='Reason for failure (if failed)', max_length=50, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='How many times was this attempt retried')),
                ('product_url', models.URLField(blank=True, help_text='URL of product found on site', null=True)),
                ('external_sku', models.CharField(blank=True, help_text='SKU from the site', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if attempt failed', null=True)),
                ('screenshot', models.ImageField(blank=True, help_text='Screenshot for debugging', null=True, upload_to='bot_failures/')),
                ('started_at', models.DateTimeField(help_text='When this site attempt started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When this site attempt completed', null=True)),
                ('execution', models.ForeignKey(help_text='Which execution this attempt is part of', on_delete=django.db.models.deletion.CASCADE, related_name='site_attempts', to='pop_up_bot.procurementexecution')),
            ],
            options={
                'verbose_name': 'Site Attempt',
                'verbose_name_plural': 'Site Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalProductReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(choices=[('nike', 'Nike'), ('footlocker', 'Footlocker'), ('adidas', 'Adidas'), ('new_balance', 'New Balance'), ('supreme', 'Supreme'), ('grailed', 'Grailed'), ('stockx', 'StockX')], db_index=True, max_length=50)),
                ('external_sku', models.CharField(help_text='SKU on the external site', max_length=255)),
                ('external_url', models.URLField(help_text='Direct link to product on external site')),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Last time we verified this product exists', null=True)),
                ('last_price_check', models.DateTimeField(blank=True, null=True)),
                ('last_known_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_references', to='pop_up_auction.popupproduct')),
            ],
            options={
                'indexes': [models.Index(fields=['site_name', 'external_sku'], name='pop_up_bot__site_na_132e93_idx')],
                'unique_together': {('site_name', 'external_sku')},
            },
        ),
        migrations.CreateModel(
            name='ProcurementEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('INITIALIZED', 'Initialized'), ('STRATEGY_SELECTED', 'Strategy Selected'), ('SITE_SELECTED', 'Site Selected'), ('PRODUCT_FOUND', 'Product Found'), ('SIZE_SELECTED', 'Size Selected'), ('CART_SUCCESS', 'Added to Cart'), ('LOCK_ACQUIRED', 'Lock Acquired'), ('LOCK_FAILED', 'Lock Failed'), ('CHECKOUT_STARTED', 'Checkout Started'), ('PAYMENT_SUBMITTED', 'Payment Submitted'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('site_name', models.CharField(blank=True, help_text='Which site this event relates to (if applicable)', max_length=50, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional event data (JSON)')),
                ('bot_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pop_up_bot.procurementexecution')),
            ],
            options={
                'verbose_name': 'Procurement Event',
                'verbose_name_plural': 'Procurement Events',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['bot_execution', 'timestamp'], name='pop_up_bot__bot_exe_bc978e_idx'), models.Index(fields=['event_type'], name='pop_up_bot__event_t_feb47b_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_identifier', models.CharField(db_index=True, help_text="External SKU or product identifier (e.g., Nike: 'DA1971-104')", max_length=255)),
                ('size', models.CharField(db_index=True, max_length=20)),
                ('site_name', models.CharField(db_index=True, help_text="Which site this lock is for (e.g., 'nike', 'footlocker')", max_length=50)),
                ('status', models.CharField(choices=[('acquired', 'Acquired'), ('released', 'Released'), ('expired', 'Expired'), ('failed', 'Failed')], db_index=True, default='acquired', max_length=20)),
                ('locked_until', models.DateTimeField(help_text='Lock automatically expires at this time (prevents deadlocks)')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(blank=True, help_text='Which execution this attempt is part of', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_locks', to='pop_up_bot.procurementexecution')),
            ],
            options={
                'ordering': ['-acquired_at'],
                'indexes': [models.Index(fields=['product_identifier', 'size', 'status'], name='pop_up_bot__product_26d843_idx'), models.Index(fields=['execution'], name='pop_up_bot__executi_7a068e_idx'), models.Index(fields=['locked_until'], name='pop_up_bot__locked__0330c9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'acquired')), fields=('product_identifier', 'size'), name='unique_active_lock_per_product_size')],
            },
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('context', models.JSONField(default=dict, help_text='Additional context (JSON)')),
                ('bot_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pop_up_bot.procurementexecution')),
            ],
            options={
                'verbose_name': 'Bot Log',
                'verbose_name_plural': 'Bot Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['bot_execution', 'timestamp'], name='pop_up_bot__bot_exe_b88d69_idx'), models.Index(fields=['level'], name='pop_up_bot__level_b471cc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='procurementrequest',
            index=models.Index(fields=['user', 'status'], name='pop_up_bot__user_id_06d519_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementrequest',
            index=models.Index(fields=['status'], name='pop_up_bot__status_db2519_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementrequest',
            index=models.Index(fields=['expires_at'], name='pop_up_bot__expires_05de7e_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementexecution',
            index=models.Index(fields=['procurement_request', 'status'], name='pop_up_bot__procure_b81daf_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementexecution',
            index=models.Index(fields=['status'], name='pop_up_bot__status_18c1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementexecution',
            index=models.Index(fields=['winning_site'], name='pop_up_bot__winning_bf3c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementexecution',
            index=models.Index(fields=['order_id'], name='pop_up_bot__order_i_86e1e5_idx'),
        ),
        migrations.AddIndex(
            model_name='siteattempt',
            index=models.Index(fields=['execution', 'site_name'], name='pop_up_bot__executi_e23b39_idx'),
        ),
        migrations.AddIndex(
            model_name='siteattempt',
            index=models.Index(fields=['status'], name='pop_up_bot__status_196bd1_idx'),
        ),
    ]
