# Generated by Django 5.1.3 on 2026-05-14 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pop_up_auction', '0002_popupproduct_pop_up_auct_product_9b7d5f_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('target_size', models.CharField(max_length=50)),
                ('target_color', models.CharField(blank=True, max_length=100, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('strategy_used', models.CharField(default='sequential', max_length=50)),
                ('sites_attempted', models.JSONField(default=list)),
                ('winning_site', models.CharField(blank=True, max_length=50, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method_type', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('gift_card', 'Gift Card')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('concierge_mode', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_executions', to='pop_up_auction.popupbrand')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_executions', to='pop_up_auction.popupproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('bot_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pop_up_bot.botexecution')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('gift_card', 'Gift Card')], max_length=50)),
                ('encrypted_number', models.BinaryField(help_text='AES-256 encrypted card/gift card number')),
                ('encrypted_csv', models.BinaryField(help_text='AES-256 encrypted CVV/CSV')),
                ('encrypted_expiry', models.BinaryField(help_text='AES-256 encrypted expiration date')),
                ('encrypted_pin', models.BinaryField(blank=True, help_text='AES-256 encrypted PIN (gift cards only)', null=True)),
                ('last_four', models.CharField(help_text='Last 4 digits for display', max_length=4)),
                ('card_holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('INITIALIZED', 'Initialized'), ('STRATEGY_SELECTED', 'Strategy Selected'), ('SITE_SELECTED', 'Site Selected'), ('PRODUCT_FOUND', 'Product Found'), ('SIZE_SELECTED', 'Size Selected'), ('CART_SUCCESS', 'Added to Cart'), ('LOCK_ACQUIRED', 'Lock Acquired'), ('LOCK_FAILED', 'Lock Failed'), ('CHECKOUT_STARTED', 'Checkout Started'), ('PAYMENT_SUBMITTED', 'Payment Submitted'), ('ORDER_CONFIRMED', 'Order Confirmed'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site_name', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('bot_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pop_up_bot.botexecution')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SiteAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=50)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('item_found', 'Item Found'), ('added_to_cart', 'Added to Cart'), ('checkout_started', 'Checkout Started'), ('payment_failed', 'Payment Failed'), ('order_confirmed', 'Order Confirmed'), ('stock_out', 'Out of Stock'), ('not_available', 'Not Available'), ('error', 'Error')], max_length=50)),
                ('product_url', models.URLField(blank=True, null=True)),
                ('product_sku', models.CharField(blank=True, help_text="Site's product SKU/ID", max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('screenshot', models.FileField(blank=True, null=True, upload_to='')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bot_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_attempts', to='pop_up_bot.botexecution')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='botexecution',
            index=models.Index(fields=['user', '-created_at'], name='pop_up_bot__user_id_4e20a0_idx'),
        ),
        migrations.AddIndex(
            model_name='botexecution',
            index=models.Index(fields=['status'], name='pop_up_bot__status_cf9ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='botexecution',
            index=models.Index(fields=['winning_site'], name='pop_up_bot__winning_d5cd89_idx'),
        ),
        migrations.AddIndex(
            model_name='botexecution',
            index=models.Index(fields=['order_id'], name='pop_up_bot__order_i_13ad1c_idx'),
        ),
        migrations.AddIndex(
            model_name='botlog',
            index=models.Index(fields=['bot_execution', 'timestamp'], name='pop_up_bot__bot_exe_b88d69_idx'),
        ),
        migrations.AddIndex(
            model_name='botlog',
            index=models.Index(fields=['level'], name='pop_up_bot__level_b471cc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'is_active'], name='pop_up_bot__user_id_d49b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementevent',
            index=models.Index(fields=['bot_execution', 'timestamp'], name='pop_up_bot__bot_exe_bc978e_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementevent',
            index=models.Index(fields=['event_type'], name='pop_up_bot__event_t_feb47b_idx'),
        ),
        migrations.AddIndex(
            model_name='siteattempt',
            index=models.Index(fields=['bot_execution', 'site_name'], name='pop_up_bot__bot_exe_4772f0_idx'),
        ),
        migrations.AddIndex(
            model_name='siteattempt',
            index=models.Index(fields=['status'], name='pop_up_bot__status_196bd1_idx'),
        ),
    ]
