# Generated by Django 5.1.3 on 2026-05-15 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_auction', '0002_popupproduct_pop_up_auct_product_9b7d5f_idx'),
        ('pop_up_bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(db_index=True, help_text="Site identifier (e.g., 'nike', 'footlocker')", max_length=50)),
                ('name', models.CharField(help_text='Cookie name', max_length=255)),
                ('value', models.TextField(help_text='Cookie value')),
                ('domain', models.CharField(help_text="Cookie domain (e.g., '.nike.com')", max_length=255)),
                ('path', models.CharField(default='/', help_text='Cookie path', max_length=255)),
                ('expires', models.DateTimeField(blank=True, help_text='Cookie expiration time', null=True)),
                ('http_only', models.BooleanField(default=False, help_text='Cookie httpOnly flag')),
                ('secure', models.BooleanField(default=False, help_text='Cookie secure flag (HTTPS only)')),
                ('same_site', models.CharField(choices=[('Lax', 'Lax'), ('Strict', 'Strict'), ('None', 'None')], default='Lax', help_text='Cookie SameSite flag', max_length=10)),
                ('saved_at', models.DateTimeField(auto_now_add=True, help_text='When this cookie was saved')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this cookie was last updated')),
            ],
            options={
                'verbose_name': 'Bot Cookie',
                'verbose_name_plural': 'Bot Cookies',
                'db_table': 'pop_up_bot_cookies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalProductReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(choices=[('nike', 'Nike'), ('footlocker', 'Footlocker'), ('adidas', 'Adidas'), ('new_balance', 'New Balance'), ('supreme', 'Supreme')], max_length=50)),
                ('external_sku', models.CharField(max_length=255)),
                ('external_url', models.URLField()),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_identifier', models.CharField(help_text="External SKU or product identifier (e.g., Nike: 'DA1971-104')", max_length=255)),
                ('size', models.CharField(max_length=20)),
                ('site_name', models.CharField(help_text="Which site this lock is for (e.g., 'nike', 'footlocker')", max_length=50)),
                ('status', models.CharField(choices=[('acquired', 'Acquired'), ('released', 'Released'), ('expired', 'Expired'), ('failed', 'Failed')], default='acquired', max_length=20)),
                ('locked_until', models.DateTimeField(help_text='Lock automatically expires at this time (prevents deadlocks)')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-acquired_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('strategy_used', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel'), ('priority', 'Priority')], default='sequential', max_length=20)),
                ('winning_site', models.CharField(blank=True, max_length=50, null=True)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('target_size', models.CharField(max_length=50)),
                ('target_color', models.CharField(blank=True, max_length=100, null=True)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('procurement_type', models.CharField(choices=[('inventory', 'Inventory Procurement'), ('concierge', 'Concierge Procurement')], default='inventory', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('priority_score', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='botexecution',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='botexecution',
            name='product',
        ),
        migrations.RemoveField(
            model_name='botexecution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='siteattempt',
            name='bot_execution',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='siteattempt',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='siteattempt',
            name='pop_up_bot__bot_exe_4772f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='siteattempt',
            name='pop_up_bot__status_196bd1_idx',
        ),
        migrations.RemoveField(
            model_name='siteattempt',
            name='attempt_number',
        ),
        migrations.RemoveField(
            model_name='siteattempt',
            name='product_sku',
        ),
        migrations.AddField(
            model_name='siteattempt',
            name='external_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteattempt',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('oos', 'Out Of Stock'), ('payment_declined', 'Payment Declined'), ('captcha', 'Captcha'), ('site_timeout', 'Site Timeout'), ('blocked', 'Blocked'), ('selector_failure', 'Selector Failure'), ('network_error', 'Network Error'), ('unknown', 'Unknown')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteattempt',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='siteattempt',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='bot_failures/'),
        ),
        migrations.AlterField(
            model_name='siteattempt',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('product_found', 'Product Found'), ('carted', 'Carted'), ('checkout_started', 'Checkout Started'), ('payment_submitted', 'Payment Submitted'), ('success', 'Success'), ('failed', 'Failed'), ('oos', 'Out Of Stock'), ('blocked', 'Blocked')], default='started', max_length=50),
        ),
        migrations.AddIndex(
            model_name='cookiemodel',
            index=models.Index(fields=['site_name', 'name'], name='pop_up_bot__site_na_24341c_idx'),
        ),
        migrations.AddIndex(
            model_name='cookiemodel',
            index=models.Index(fields=['site_name', '-updated_at'], name='pop_up_bot__site_na_eb8921_idx'),
        ),
        migrations.AddIndex(
            model_name='cookiemodel',
            index=models.Index(fields=['expires'], name='pop_up_bot__expires_60b519_idx'),
        ),
        migrations.AddConstraint(
            model_name='cookiemodel',
            constraint=models.UniqueConstraint(fields=('site_name', 'domain', 'name'), name='unique_site_domain_cookie_name'),
        ),
        migrations.AddField(
            model_name='externalproductreference',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_references', to='pop_up_auction.popupproduct'),
        ),
        migrations.AddField(
            model_name='inventorylock',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_locks', to='pop_up_bot.procurementexecution'),
        ),
        migrations.AddField(
            model_name='siteattempt',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_attempts', to='pop_up_bot.procurementexecution'),
        ),
        migrations.AlterField(
            model_name='botlog',
            name='bot_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pop_up_bot.procurementexecution'),
        ),
        migrations.AlterField(
            model_name='procurementevent',
            name='bot_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pop_up_bot.procurementexecution'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pop_up_auction.popupbrand'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pop_up_auction.popupproduct'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementexecution',
            name='procurement_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='pop_up_bot.procurementrequest'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.AddIndex(
            model_name='inventorylock',
            index=models.Index(fields=['product_identifier', 'size', 'status'], name='pop_up_bot__product_26d843_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylock',
            index=models.Index(fields=['execution'], name='pop_up_bot__executi_7a068e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylock',
            index=models.Index(fields=['locked_until'], name='pop_up_bot__locked__0330c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorylock',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'acquired')), fields=('product_identifier', 'size'), name='unique_active_lock_per_product_size'),
        ),
        migrations.DeleteModel(
            name='BotExecution',
        ),
    ]
