# Generated by Django 5.1.3 on 2026-05-30 23:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_auction', '0002_popupproduct_pop_up_auct_product_9b7d5f_idx'),
        ('pop_up_bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, help_text='Nike SKU (e.g., IQ8495-002)', max_length=50)),
                ('release_date', models.DateTimeField(db_index=True, help_text='Exact time product becomes available on Nike')),
                ('procurement_window_minutes', models.PositiveIntegerField(default=30, help_text='How many minutes after release time to keep attempting to buy (default 30)')),
                ('search_method', models.CharField(choices=[('direct_url', 'Direct URL - Go straight to product page'), ('sku_search', 'SKU Search - Search Nike by SKU'), ('product_name', 'Product Name - Search by name')], default='direct_url', help_text='How the bot should find this product on Nike', max_length=20)),
                ('product_url', models.URLField(blank=True, help_text='Direct Nike product URL (e.g., https://www.nike.com/t/...)', null=True)),
                ('search_query', models.CharField(blank=True, help_text='Product name to search for if direct URL fails', max_length=255, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled - Waiting for release time'), ('active', 'Active - Release time has arrived, bot running'), ('completed', 'Completed - Release window closed'), ('cancelled', 'Cancelled - Admin cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for scheduled release', max_length=255, null=True)),
                ('nike_product_name', models.CharField(blank=True, help_text='Exact product name from Nike (if already ran once)', max_length=255, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, help_text='Expected retail price', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='The PopUpProduct being released', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_releases', to='pop_up_auction.popupproduct')),
            ],
            options={
                'verbose_name': 'Scheduled Release',
                'verbose_name_plural': 'Scheduled Releases',
                'ordering': ['release_date'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseExecutionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_attempts', models.PositiveIntegerField(default=0, help_text='Total executions attempted')),
                ('successful_count', models.PositiveIntegerField(default=0, help_text='How many succeeded')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='How many failed')),
                ('started_at', models.DateTimeField(help_text='When we started executing')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When all executions finished', null=True)),
                ('notes', models.TextField(blank=True, help_text="Any notes about this release (e.g., 'Nike was slow')", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executions', models.ManyToManyField(help_text='All executions in this batch', related_name='release_batch', to='pop_up_bot.procurementexecution')),
                ('scheduled_release', models.ForeignKey(help_text='The release this batch was for', on_delete=django.db.models.deletion.CASCADE, related_name='execution_batches', to='pop_up_bot.scheduledrelease')),
            ],
            options={
                'verbose_name': 'Release Execution Batch',
                'verbose_name_plural': 'Release Execution Batches',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(help_text='Size they want (e.g., US 10)', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Preferred color if available', max_length=100, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text="Max price they'll pay (optional)", max_digits=10, null=True)),
                ('strategy', models.CharField(choices=[('fastest', 'Fastest - Use fastest strategy available'), ('cheapest', 'Cheapest - Try to find lowest price'), ('standard', 'Standard - Sequential attempts')], default='fastest', help_text='Which strategy to use', max_length=20)),
                ('service_fee', models.DecimalField(decimal_places=2, help_text='Amount user paid for this service', max_digits=10)),
                ('fee_paid_at', models.DateTimeField(help_text='When user paid the fee')),
                ('status', models.CharField(choices=[('pending', 'Pending - User paid, waiting for release'), ('active', 'Active - Release time has arrived, bot running'), ('success', 'Success - Bot secured item'), ('failed', 'Failed - Bot could not secure'), ('abandoned', 'Abandoned - User cancelled before release'), ('expired', 'Expired - Release window closed without success')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurement_request_created_at', models.DateTimeField(blank=True, help_text='When ProcurementRequest was created (at release time)', null=True)),
                ('procurement_execution', models.OneToOneField(blank=True, help_text='The execution result (if successful)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request', to='pop_up_bot.procurementexecution')),
                ('procurement_request', models.OneToOneField(blank=True, help_text='The ProcurementRequest created at release time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request', to='pop_up_bot.procurementrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_service_requests', to=settings.AUTH_USER_MODEL)),
                ('scheduled_release', models.ForeignKey(help_text='The release this user paid for', on_delete=django.db.models.deletion.CASCADE, related_name='procurement_service_requests', to='pop_up_bot.scheduledrelease')),
            ],
            options={
                'verbose_name': 'Procurement Service Request',
                'verbose_name_plural': 'Procurement Service Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledrelease',
            index=models.Index(fields=['sku', 'release_date'], name='pop_up_bot__sku_46d2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledrelease',
            index=models.Index(fields=['status', 'release_date'], name='pop_up_bot__status_b6e99b_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementservicerequest',
            index=models.Index(fields=['user', 'status'], name='pop_up_bot__user_id_46e578_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementservicerequest',
            index=models.Index(fields=['scheduled_release', 'status'], name='pop_up_bot__schedul_7de1e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='procurementservicerequest',
            unique_together={('user', 'scheduled_release', 'size')},
        ),
    ]
