# Generated by Django 5.1.3 on 2026-06-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_bot', '0002_scheduledrelease_releaseexecutionbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementexecution',
            name='error_type',
            field=models.CharField(blank=True, choices=[('bot_crash', 'Bot Crashed'), ('rate_limited', 'Rate Limited'), ('site_structure_changed', 'Site Structure Changed'), ('exception', 'Unhandled Exception'), ('unknown_error', 'Unknown Error'), ('out_of_stock', 'Out of Stock'), ('lost_to_bots', 'Lost to Other Bots'), ('item_not_found', 'Item Not Found'), ('sold_out', 'Sold Out'), ('coming_soon', 'Coming Soon'), ('payment_already_exists', 'Payment Already Exists'), ('success', 'Success')], help_text='Type of error - determines if refund should be issued', max_length=30, null=True),
        ),
    ]
