# Generated by Django 5.1.3 on 2026-06-08 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_bot', '0003_procurementexecution_error_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('nike', 'Nike'), ('footlocker', 'Footlocker'), ('adidas', 'Adidas'), ('other', 'Other')], help_text='Which site to test', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Health check status', max_length=20)),
                ('product_sku', models.CharField(help_text='Test product SKU (e.g., DJ0646-610 for Nike)', max_length=100)),
                ('product_name', models.CharField(blank=True, help_text='Name of test product', max_length=255)),
                ('steps_completed', models.JSONField(default=list, help_text="List of completed steps: ['navigate', 'search', 'add_to_cart', 'remove_from_cart']")),
                ('error_step', models.CharField(blank=True, help_text='Which step failed (if any)', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if health check failed', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When health check started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When health check completed', null=True)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='How long the health check took', null=True)),
                ('admin_notified', models.BooleanField(default=False, help_text='Whether admin was notified of failure')),
                ('admin_notification_sent_at', models.DateTimeField(blank=True, help_text='When notification was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Health Check',
                'verbose_name_plural': 'Daily Health Checks',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['site', '-created_at'], name='pop_up_bot__site_f0cad2_idx'), models.Index(fields=['status', '-created_at'], name='pop_up_bot__status_e87b4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthCheckNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('sms', 'SMS'), ('in_app', 'In App')], max_length=20)),
                ('recipient', models.CharField(help_text='Email, phone, Slack ID, etc', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False, help_text='Whether notification was successfully sent')),
                ('error_message', models.TextField(blank=True, help_text='Error if notification failed to send')),
                ('health_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pop_up_bot.dailyhealthcheck')),
            ],
            options={
                'verbose_name': 'Health Check Notification',
                'verbose_name_plural': 'Health Check Notifications',
                'ordering': ('-sent_at',),
            },
        ),
        migrations.CreateModel(
            name='HealthCheckStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(help_text='Order of execution (1, 2, 3, etc)')),
                ('step_name', models.CharField(help_text='Step description (navigate, search, add_to_cart, etc)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, help_text='What this step does')),
                ('error_message', models.TextField(blank=True, help_text='Error if step failed', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration in milliseconds', null=True)),
                ('url', models.URLField(blank=True, help_text='URL being tested')),
                ('selector_used', models.CharField(blank=True, help_text='CSS selector that was used', max_length=255)),
                ('element_found', models.BooleanField(default=False, help_text='Whether element was found')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about step')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_check', models.ForeignKey(help_text='Parent health check', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pop_up_bot.dailyhealthcheck')),
            ],
            options={
                'verbose_name': 'Health Check Step',
                'verbose_name_plural': 'Health Check Steps',
                'ordering': ('step_number',),
            },
        ),
    ]
