# Generated by Django 5.1.3 on 2026-06-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_bot', '0004_dailyhealthcheck_healthchecknotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementservicerequest',
            name='sex',
            field=models.CharField(blank=True, help_text='Gender sizing (Mens/Womens) - applicable for shoes or sneakers only', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='procurementservicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending - User paid, waiting for release'), ('pending_payment', 'Pending Payment - Awaiting service fee payment'), ('active', 'Active - Release time has arrived, bot running'), ('success', 'Success - Bot secured item'), ('failed', 'Failed - Bot could not secure'), ('abandoned', 'Abandoned - User cancelled before release'), ('expired', 'Expired - Release window closed without success')], db_index=True, default='pending', max_length=20),
        ),
    ]
