# Generated by Django 5.1.3 on 2026-06-26 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_bot', '0005_procurementservicerequest_sex_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='target_sex',
            field=models.CharField(blank=True, help_text='Gender sizing (Mens/Womens) — for shoes only', max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='procurementservicerequest',
            unique_together={('user', 'scheduled_release', 'size', 'sex')},
        ),
    ]
