# Generated by Django 5.1.3 on 2026-07-10 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_accounts', '0002_alter_popupcustomerprofile_user'),
        ('pop_up_bot', '0006_procurementrequest_target_sex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Human-readable label e.g. 'Nike Visa ending 4242' or 'Nike Gift Card #3'", max_length=100)),
                ('method_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('gift_card', 'Gift Card')], default='credit_card', max_length=20)),
                ('encrypted_number', models.TextField(help_text='Encrypted card number or gift card number')),
                ('encrypted_cvv', models.TextField(blank=True, help_text='Encrypted CVV (credit cards only)', null=True)),
                ('encrypted_expiry', models.TextField(blank=True, help_text='Encrypted expiry MM/YY (credit cards only)', null=True)),
                ('encrypted_pin', models.TextField(blank=True, help_text='Encrypted PIN (gift cards only)', null=True)),
                ('last_four', models.CharField(help_text='Last 4 digits — for display only', max_length=4)),
                ('available_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Known available balance. Null = unknown (credit cards). Required for gift cards.', max_digits=10, null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='True while a bot is actively using this card')),
                ('locked_at', models.DateTimeField(blank=True, help_text='When the lock was acquired', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive cards are never selected by the bot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_address', models.ForeignKey(blank=True, help_text='Billing address on file for this card', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pop_accounts.popupcustomeraddress')),
                ('locked_by_execution', models.ForeignKey(blank=True, help_text='Which execution currently holds this card', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_payment_method', to='pop_up_bot.procurementexecution')),
            ],
            options={
                'verbose_name': 'Bot Payment Method',
                'verbose_name_plural': 'Bot Payment Methods',
                'ordering': ['-created_at'],
            },
        ),
    ]
