# Generated by Django 5.1.3 on 2025-06-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupcartitem',
            name='buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
