# Generated by Django 5.1.3 on 2026-01-18 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popuporderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
