# Generated by Django 5.1.3 on 2026-06-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_order', '0002_alter_popuporderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popuporderitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
