# Generated by Django 5.1.3 on 2025-12-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winnerreservation',
            options={'verbose_name': 'PopUp Winner Reservation', 'verbose_name_plural': 'PopUp Winner Reservations'},
        ),
        migrations.AlterField(
            model_name='popupproductimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a product image', null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
