# Generated by Django 5.1.3 on 2026-05-14 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop_up_auction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='popupproduct',
            index=models.Index(fields=['product_title'], name='pop_up_auct_product_9b7d5f_idx'),
        ),
    ]
