# Generated by Django 5.1.3 on 2025-06-06 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('pop_accounts', '0007_popupcustomeraddress_is_default_billing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupcustomerorder',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_billing', to='pop_accounts.popupcustomeraddress'),
        ),
        migrations.AddField(
            model_name='popupcustomerorder',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_shipping', to='pop_accounts.popupcustomeraddress'),
        ),
    ]
