# Generated by Django 5.1.3 on 2025-06-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_popupcustomerorder_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupcustomerorder',
            name='address2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='popupcustomerorder',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
