# Generated by Django 5.1.3 on 2025-06-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_popupcustomerorder_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popupcustomerorder',
            old_name='stripe_id',
            new_name='payment_data_id',
        ),
    ]
