# Generated by Django 5.1.3 on 2025-06-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_stripe_id_popupcustomerorder_payment_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='popuporderitem',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='popuporderitem',
            name='product_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popuporderitem',
            name='secondary_product_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='popuporderitem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
