# Generated by Django 5.1.3 on 2025-06-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_popuporderitem_color_popuporderitem_product_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popuporderitem',
            options={'ordering': ('-order',), 'verbose_name': 'PopUpOrderItem', 'verbose_name_plural': 'PopUpOrderItems'},
        ),
        migrations.AlterField(
            model_name='popupcustomerorder',
            name='order_key',
            field=models.CharField(max_length=3500),
        ),
        migrations.AlterField(
            model_name='popuporderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
