# Generated by Django 5.1.3 on 2025-06-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_popuporderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popupcustomerorder',
            name='order_key',
            field=models.CharField(max_length=200),
        ),
    ]
