# Generated by Django 5.1.3 on 2025-06-28 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_popupcustomerorder_order_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popupcustomerorder',
            options={'ordering': ('-created_at',), 'verbose_name': 'Pop Up Customer Order', 'verbose_name_plural': 'Pop Up Customer Orders'},
        ),
        migrations.AlterModelOptions(
            name='popuporderitem',
            options={'ordering': ('-order',), 'verbose_name': 'PopUp Order Item', 'verbose_name_plural': 'PopUp Order Items'},
        ),
    ]
